default:
  image: ghcr.zexi.me/wangzexi/gitlab-runner-env:main


include:
  - project: 'library/ci'
    file: 'job/docker.yml'
  - project: 'library/ci'
    file: 'job/gateway.yml'


variables:
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  # DEPLOY_HOST: bj.i.zexi.me # 部署的目标主机
  # GATEWAY_HOST: bj.i.zexi.me # 运行 caddy 网关的主机
  # GATEWAY_SITE: app.zexi.love # Caddyfile 网关规则的虚拟主机
  DEPLOY_USER: root
  GATEWAY_USER: root


stages:
  - prepare
  - build
  - deploy


prepare:
  stage: prepare
  environment:
    name: $CI_COMMIT_REF_SLUG
  script:
    - echo 部署目标 $DEPLOY_HOST
    - echo 部署网关 $GATEWAY_HOST
    - echo 部署站点 $GATEWAY_SITE
    - |
      if [ -z "$DEPLOY_HOST" ]; then
        echo "部署目标 DEPLOY_HOST 为空";
        exit 1;
      fi
    - |
      if [ -z "$GATEWAY_HOST" ]; then
        if [ -n "$GATEWAY_SITE" ]; then
          echo "部署站点 GATEWAY_SITE 为空";
          exit 1;
        fi
      else
        if [ -z "$GATEWAY_SITE" ]; then
          echo "部署网关 GATEWAY_SITE 为空";
          exit 1;
        fi
      fi


build:
  stage: build
  script:
    - docker pull $IMAGE_TAG || true
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $IMAGE_TAG


deploy-docker:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    on_stop: teardown-docker
  extends:
    - .docker_deploy

teardown-docker:
  stage: deploy
  needs:
    - deploy-docker
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
  allow_failure: true
  extends:
    - .docker_teardown
  when: manual


deploy-gateway:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
    on_stop: teardown-gateway
  extends:
    - .gateway_add
  rules:
    - if: $GATEWAY_HOST && $GATEWAY_SITE
      when: on_success
    - when: never

teardown-gateway:
  stage: deploy
  needs:
    - deploy-gateway
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
  allow_failure: true
  extends:
    - .gateway_remove
  rules:
    - if: $GATEWAY_HOST && $GATEWAY_SITE
      when: manual
    - when: never
